Create hagiwara-can
wakkihaya/neurotechjp pull request #106
Opened 2021-11-07 15:19 UTC by shoukak

確認よろ

2021-11-07 15:26 UTC, shoukak commented
バナー画像がアップロードされてないと思うから、それもおなしゃす

2021-11-08 01:42 UTC, wakkihaya requested changes
`hagiwara-can.md` に変えてください！

`yarn dev` すると localhost:3000 でページが見えるのでそれで諸々修正等あれば、自分で直して欲しい 🙏 
(一応、PR内にあるVercel のPreviewからもコミット後のWebページは見えるけど、ベースは自分のローカルのページでの確認お願いします〜）

萩原さんの画像は `main` ブランチにあげました〜
`git merge main` で取り込み可能で、 `/img/hagiwara-can/ogp.jpg` にある！

2021-11-08 08:59 UTC, shoukak commented
localで確認、修正完了した！

2021-11-08 09:22 UTC, wakkihaya requested changes

2021-11-08 09:22 UTC, wakkihaya commented on src/md/jp/blog/hagiwara-can.md
> +bannerPhoto: '/img/hagiwara-can/ogp.png'
ogp.jpg に変更plz!

2021-11-08 09:27 UTC, shoukak commented
変更した！

2021-11-08 09:37 UTC, merged